Repository process-analytics/bpmn-visualization-pm4py, pull requests merged in 2023-02, with the labels that each got.

#8 [DOC] Update licenses
  LICENSE
  README.md
  frontend/src/legend.js
  third_party/bpmn-visualization.LICENSE
  third_party/d3.LICENSE
  third_party/observable.LICENSE
Labels: documentation

#16 chore: ensure that the PR title follows "Conventional Commits"
  .github/dependabot.yml
  .github/workflows/pr-metadata-checks.yml
Labels: chore

#19 chore: add a 'backend mock server' to ease frontend development
  README.md
  backend-mock-server/.eslintrc.js
  backend-mock-server/.gitignore
  backend-mock-server/.prettierrc
  backend-mock-server/README.md
  backend-mock-server/nest-cli.json
  backend-mock-server/package-lock.json
  backend-mock-server/package.json
  backend-mock-server/src/app.controller.spec.ts
  backend-mock-server/src/app.controller.ts
  backend-mock-server/src/app.module.ts
  backend-mock-server/src/app.service.ts
  backend-mock-server/src/assets/diagram.bpmn
  backend-mock-server/src/assets/diagram.ts
  backend-mock-server/src/main.ts
  backend-mock-server/test/app.e2e-spec.ts
  backend-mock-server/test/jest-e2e.json
  backend-mock-server/tsconfig.build.json
  backend-mock-server/tsconfig.json
  frontend/package.json
  frontend/src/conversion.js
Labels: chore

#26 fix(conformance): fix typo in legend
  frontend/src/conformance.js
Labels: bug

#27 refactor(frontend): retrieve the mxgraph context
  frontend/package.json
  frontend/src/conformance.js
  frontend/src/discovery.js
  frontend/src/mxgraph-initializer.ts
Labels: refactoring
