Repository process-analytics/bpmn-visualization-pm4py, pull requests merged in 2023-07, with the labels that each got.

#37 chore(frontend): allow all node 18 versions
  frontend/.nvmrc
Labels: chore

#38 chore(frontend): bump dependencies
  .gitignore
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#40 refactor: use resetStyle API
  frontend/src/conformance.js
Labels: refactoring

#41 bug: check NaN frequencies
  frontend/src/discovery.js
Labels: bug
